apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: ltimad
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwNS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYkc5bmFXNTBiMkYzYzBCbmJXRnBiQzVqYjIwNlZtRnNZWGg1UURFeU13PT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
